version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - STORAGE_TYPE=postgres
      - POSTGRES_CONN_STRING=host=db port=5432 user=postgres password=postgres dbname=goshorten sslmode=disable
    depends_on:
      - db
    networks:
      - goshorten-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goshorten
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - goshorten-network

volumes:
  postgres_data:

networks:
  goshorten-network:
    driver: bridge 